services:
  mongodb:
    image: mongo:latest
    container_name: nammongodb-prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_prod_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - prod-net

  product-api:
    image: cato1209/product-api:latest
    container_name: product-api-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/productdb
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - prod-net

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 product-api-prod
    environment:
      - WATCHTOWER_CLEANUP=true
    networks:
      - prod-net

volumes:
  mongo_prod_data:

networks:
  prod-net:
    driver: bridge